# Generated by Django 5.0.1 on 2024-01-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mctkd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=15)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_inscripcion', models.DateField()),
                ('celular', models.CharField(max_length=12, null=True)),
                ('foto', models.ImageField(null=True, upload_to='alumno_fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=15)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=12, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('Distrito', models.CharField(max_length=100)),
                ('Provincia', models.CharField(max_length=100)),
                ('Departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cinturon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinturon_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.IntegerField()),
                ('dia_semana', models.CharField(max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=15)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('celular', models.CharField(max_length=12, null=True)),
                ('foto', models.ImageField(null=True, upload_to='profesor_fotos')),
                ('sexo', models.CharField(max_length=15)),
                ('estado_civil', models.CharField(max_length=15)),
                ('hijos', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('Distrito', models.CharField(max_length=100)),
                ('Provincia', models.CharField(max_length=100)),
                ('Departamento', models.CharField(max_length=100)),
            ],
        ),
    ]
