# Generated by Django 5.0.1 on 2024-01-24 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mctkd', '0002_alumno_apoderado_categoria_cinturon_horario_pension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='apoderado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='mctkd.apoderado'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='categoria',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='mctkd.categoria'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='cinturon',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='mctkd.cinturon'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='horario',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='mctkd.horario'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='sede',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='mctkd.sede'),
        ),
        migrations.AddField(
            model_name='horario',
            name='profesor',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='mctkd.profesor'),
        ),
        migrations.AddField(
            model_name='horario',
            name='sede',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='mctkd.sede'),
        ),
        migrations.AddField(
            model_name='pension',
            name='alumno',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='mctkd.alumno'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='cinturon',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='mctkd.cinturon'),
        ),
    ]
